# Generated by Django 6.0.6 on 2026-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="alert",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
    ]
