# Generated by Django 6.0.6 on 2026-07-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0003_healthcheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("CPU", "CPU Usage"),
                            ("MEMORY", "Memory Usage"),
                            ("DISK", "Disk Usage"),
                            ("API", "API Response Time"),
                            ("WEBSITE", "Website Response Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", "Greater Than (>)"),
                            ("<", "Less Than (<)"),
                            (">=", "Greater Than or Equal (>=)"),
                            ("<=", "Less Than or Equal (<=)"),
                            ("==", "Equal (==)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("threshold", models.FloatField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE_ALERT", "Create Alert"),
                            ("SEND_EMAIL", "Send Email"),
                            ("RETRY_API", "Retry API"),
                            ("RESTART_SERVICE", "Restart Service"),
                            ("BROWSER_AUTOMATION", "Run Browser Automation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=1)),
                ("cooldown_seconds", models.PositiveIntegerField(default=300)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="monitoring.server",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "name"),
            },
        ),
    ]
