"""
Alert models for EIAP.

This module stores infrastructure alerts generated by the
Automation Engine.

An Alert represents an operational incident that requires
attention.

Example

CPU > 90%

↓

Automation Rule Matches

↓

Alert Created

↓

Dashboard

↓

Email Notification

↓

Resolved
"""

# Import Django's model classes.
from django.db import models

# Import related models.
from apps.monitoring.models import Metric, Server
from apps.automation.models import AutomationRule
from django.utils import timezone


# ==========================================================
# Alert Severity
# ==========================================================
#
# Indicates how serious an alert is.
#
# ==========================================================

class AlertSeverity(models.TextChoices):
    """
    Alert severity levels.
    """

    INFO = "INFO", "Information"

    WARNING = "WARNING", "Warning"

    CRITICAL = "CRITICAL", "Critical"


# ==========================================================
# Alert Status
# ==========================================================
#
# Represents the lifecycle of an alert.
#
# ==========================================================

class AlertStatus(models.TextChoices):
    """
    Current state of an alert.
    """

    OPEN = "OPEN", "Open"

    ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged"

    RESOLVED = "RESOLVED", "Resolved"


# ==========================================================
# Alert Model
# ==========================================================

class Alert(models.Model):
    """
    Represents an incident detected by EIAP.
    """

    # ------------------------------------------------------
    # Server that generated the alert.
    # ------------------------------------------------------
    server = models.ForeignKey(
        Server,
        on_delete=models.CASCADE,
        related_name="alerts",
    )

    # ------------------------------------------------------
    # Rule responsible for generating this alert.
    # ------------------------------------------------------
    rule = models.ForeignKey(
        AutomationRule,
        on_delete=models.CASCADE,
        related_name="alerts",
    )

    # ------------------------------------------------------
    # Metric that triggered the alert.
    #
    # This lets us inspect the exact CPU/Memory/Disk values
    # that caused the incident.
    # ------------------------------------------------------
    metric = models.ForeignKey(
        Metric,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="alerts",
    )

    # Short alert title.
    name = models.CharField(
        max_length=150,
    )

    # Detailed description.
    message = models.TextField()

    # Alert severity.
    severity = models.CharField(
        max_length=20,
        choices=AlertSeverity.choices,
        default=AlertSeverity.WARNING,
    )

    # Current alert status.
    status = models.CharField(
        max_length=20,
        choices=AlertStatus.choices,
        default=AlertStatus.OPEN,
    )

    # Time the alert was created.
    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    # Time the alert was resolved.
    resolved_at = models.DateTimeField(
        null=True,
        blank=True,
    )
    # User who acknowledged the alert.
    acknowledged_by = models.CharField(
        max_length=100,
        blank=True,
    )

    # Time acknowledgement occurred.
    acknowledged_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    # Notes entered by administrator.
    resolution_notes = models.TextField(
        blank=True,
    )

    class Meta:
        """
        Django model configuration.
        """

        ordering = (
            "-created_at",
        )

    def __str__(self):
        """
        Human-readable representation.
        """

        return (
            f"{self.server.name} - "
            f"{self.name}"
        )

    def acknowledge(self, username):
        """
        Mark the alert as acknowledged.
        """

        self.status = AlertStatus.ACKNOWLEDGED
        self.acknowledged_by = username
        self.acknowledged_at = timezone.now()
        self.save()

    def resolve(self, notes=""):
        """
        Resolve the alert.
        """

        self.status = AlertStatus.RESOLVED
        self.resolution_notes = notes
        self.resolved_at = timezone.now()
        self.save()
