# Generated by Django 6.0.6 on 2026-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "host",
                    models.CharField(
                        help_text="Hostname or IP address", max_length=255
                    ),
                ),
                ("port", models.PositiveIntegerField(default=80)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("SERVER", "Server"),
                            ("WEBSITE", "Website"),
                            ("API", "API"),
                            ("DATABASE", "Database"),
                        ],
                        default="SERVER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
