# Generated by Django 6.0.6 on 2026-07-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("CPU", "CPU"),
                            ("MEMORY", "Memory"),
                            ("DISK", "Disk"),
                            ("API", "API"),
                            ("WEBSITE", "Website"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Execution interval in seconds."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_jobs",
                        to="monitoring.server",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_usage", models.FloatField()),
                ("memory_usage", models.FloatField()),
                ("disk_usage", models.FloatField()),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(default="Healthy", max_length=30)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="monitoring.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["server"], name="monitoring__server__03b9be_idx"
                    ),
                    models.Index(
                        fields=["collected_at"], name="monitoring__collect_87d738_idx"
                    ),
                ],
            },
        ),
    ]
