# Generated by Django 6.0.6 on 2026-07-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoringjob_metric"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("execution_time_ms", models.PositiveIntegerField()),
                ("http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("screenshot_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitoring_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="monitoring.monitoringjob",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="monitoring.server",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["server"], name="monitoring__server__70c157_idx"
                    ),
                    models.Index(
                        fields=["status"], name="monitoring__status_8e51ed_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="monitoring__started_1e055c_idx"
                    ),
                ],
            },
        ),
    ]
