# Generated by Django 6.0.6 on 2026-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_healthcheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="endpoint",
            field=models.URLField(blank=True, help_text="API or Website URL."),
        ),
    ]
