# Generated by Django 6.0.6 on 2026-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_server_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="endpoint",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
